# This file was generated by GoReleaser. DO NOT EDIT.
cask "soko" do
  version "0.18.0"

  on_macos do
    on_intel do
      url "https://github.com/CelikE/soko/releases/download/v#{version}/soko_#{version}_darwin_amd64.tar.gz"
      sha256 "59e459c76aeeadb106ab87c76269306a08dcb42b7aedfa679172993cb0e303d0"
    end
    on_arm do
      url "https://github.com/CelikE/soko/releases/download/v#{version}/soko_#{version}_darwin_arm64.tar.gz"
      sha256 "8bdaf07b4e2ab35b09407bfc7a5d59396ba1b50046f728168e00cdf397a4f362"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/CelikE/soko/releases/download/v#{version}/soko_#{version}_linux_amd64.tar.gz"
      sha256 "a1c34d3af48b3a2732a06e3dc660982ff9509ad1a060164375706146ea74218f"
    end
    on_arm do
      url "https://github.com/CelikE/soko/releases/download/v#{version}/soko_#{version}_linux_arm64.tar.gz"
      sha256 "48097fb6046f3fccf802115ab717126757a5305f416bbe42708a6f1279ef107e"
    end
  end

  name "soko"
  desc "A fast CLI to manage multiple git repositories at once."
  homepage "https://github.com/CelikE/soko"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "soko"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/soko"]
    end
  end

  # No zap stanza required

end
