# This file was generated by GoReleaser. DO NOT EDIT.
cask "soko" do
  version "0.16.0"

  on_macos do
    on_intel do
      url "https://github.com/CelikE/soko/releases/download/v#{version}/soko_#{version}_darwin_amd64.tar.gz"
      sha256 "5a903af3543675752b88c5806ade865c4635fba540f63350717566f3ddecee3d"
    end
    on_arm do
      url "https://github.com/CelikE/soko/releases/download/v#{version}/soko_#{version}_darwin_arm64.tar.gz"
      sha256 "2b409c4042160585a72247f9e7de16d30ce8e930ee52483050fb38676c47b196"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/CelikE/soko/releases/download/v#{version}/soko_#{version}_linux_amd64.tar.gz"
      sha256 "200c95aee1a4705aa94ee8a6d56fc497bb0e9f14de2663e68c559e49fe277f97"
    end
    on_arm do
      url "https://github.com/CelikE/soko/releases/download/v#{version}/soko_#{version}_linux_arm64.tar.gz"
      sha256 "74cdd0b750f8d6b37f27f5e919e1372fb7b63063c66a495173f4b743b1ba8a5e"
    end
  end

  name "soko"
  desc "A fast CLI to manage multiple git repositories at once."
  homepage "https://github.com/CelikE/soko"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "soko"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/soko"]
    end
  end

  # No zap stanza required

end
