# This file was generated by GoReleaser. DO NOT EDIT.
cask "soko" do
  version "0.18.1"

  on_macos do
    on_intel do
      url "https://github.com/CelikE/soko/releases/download/v#{version}/soko_#{version}_darwin_amd64.tar.gz"
      sha256 "2c6f2dc1fda3ad7b16e2dffd39dce55418ba3c4e7973209939a6f59c36479703"
    end
    on_arm do
      url "https://github.com/CelikE/soko/releases/download/v#{version}/soko_#{version}_darwin_arm64.tar.gz"
      sha256 "314a14b264ad6bbf1f18aaa3b48966f8192e9a4b747a6de3cefda00ebec64757"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/CelikE/soko/releases/download/v#{version}/soko_#{version}_linux_amd64.tar.gz"
      sha256 "4cddbefd3232da619d918b4335e7ccc708915c9705070440e0948be270aeb329"
    end
    on_arm do
      url "https://github.com/CelikE/soko/releases/download/v#{version}/soko_#{version}_linux_arm64.tar.gz"
      sha256 "def0815078ef84a3db4d9f37a9893c4b06b48526589d32d841da205cc4216bc4"
    end
  end

  name "soko"
  desc "A fast CLI to manage multiple git repositories at once."
  homepage "https://github.com/CelikE/soko"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "soko"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/soko"]
    end
  end

  # No zap stanza required

end
